<?php

declare(strict_types=1);

/**
 * This file is part of the EaseTWBootstrap3 package
 *
 * https://github.com/VitexSoftware/php-ease-twbootstrap
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Ease\TWB;

use Ease\TWB\ButtonGroup;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-26 at 19:03:14.
 */
class ButtonGroupTest extends \Test\Ease\Html\DivTagTest
{
    public string $rendered = '<div role="group" class="btn-group" aria-label="testGroup"></div>';
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ButtonGroup('testGroup');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Ease\TWB\ButtonGroup::addButton
     *
     * @todo   Implement testAddButton().
     */
    public function testAddButton(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }
}
